spring:
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://db:5432/vibepay
      username: vibepay
      password: vibepay
      driver-class-name: org.postgresql.Driver
    secondary:
      jdbc-url: jdbc:postgresql://db:5432/vibepay
      username: vibepay
      password: vibepay
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
