# Vibe Pay API Application Configuration

spring:
  application:
    name: vibe-pay-api

  profiles:
    active: local

  # 데이터베이스 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vibepay
    username: vibepay_user
    password: vibepay_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false


# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.vibe.pay.domain.*.entity,com.vibe.pay.domain.*.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: false
    jdbc-type-for-null: NULL
    call-setters-on-nulls: true

# Server 설정
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-stacktrace: on_param

# 로깅 설정
logging:
  level:
    root: INFO
    com.vibe.pay: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/vibe-pay-api.log
    max-size: 10MB
    max-history: 30

# SpringDoc OpenAPI (Swagger) 설정
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: false

# PG사 연동 설정 (테스트용)
pg:
  inicis:
    enabled: true
    api-url: https://iniapi.inicis.com/api
    test-api-url: https://iniapi.inicis.com/api
    mid: INIpayTest
    api-key: SU5JTElURV9UUklQTEVERVNfS0VZU1RS
    secret-key: V3d4aE1FcDBjbU12Y3k5aGNHa3ZjR0Y1TDNCaGVRPT0=
    timeout: 30000
    weight: 50
  nicepay:
    enabled: true
    api-url: https://api.nicepay.co.kr/v1
    test-api-url: https://sandbox-api.nicepay.co.kr/v1
    mid: nicepay00m
    api-key: NICEPAYTESTAPIKey123456
    secret-key: NICEPAYTESTSecretKey123456
    timeout: 30000
    weight: 50

# CORS 설정
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  exposed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true
  max-age: 3600

# 비즈니스 설정
business:
  reward-points:
    earn-rate: 0.01  # 1% 적립
    min-order-amount: 10000  # 최소 주문 금액 (포인트 적립 대상)

---
# 로컬 개발 환경
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/vibepay
    username: vibepay_user
    password: vibepay_password

logging:
  level:
    com.vibe.pay: DEBUG
    org.springframework.jdbc: DEBUG

pg:
  inicis:
    api-url: https://iniapi.inicis.com/api
  nicepay:
    api-url: https://sandbox-api.nicepay.co.kr/v1