logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

# 공통 설정
inicis:
  mid: INIpayTest
  signKey: SU5JTElURV9UUklQTEVERVNfS0VZU1RS
  version: 1.0
  currency: WON
  gopaymethod: Card
  acceptmethod: below1000
  # 프론트엔드 SSR 페이지로 복귀 (POST body 처리)
  returnUrl: http://localhost:3000/order/progress
  closeUrl: http://localhost:3000/order/close

# 개발 환경
---
spring:
  config:
    activate:
      on-profile: dev
inicis:
  mid: ${INICIS_MID:INIpayTest}
  signKey: ${INICIS_SIGN_KEY:INIpayTest}
  returnUrl: ${INICIS_RETURN_URL:http://localhost:3000/order/return}
  closeUrl: ${INICIS_CLOSE_URL:http://localhost:3000/order/close}

# 검증(staging/test) 환경
---
spring:
  config:
    activate:
      on-profile: test
inicis:
  mid: ${INICIS_MID}
  signKey: ${INICIS_SIGN_KEY}
  returnUrl: ${INICIS_RETURN_URL}
  closeUrl: ${INICIS_CLOSE_URL}

# 운영 환경
---
spring:
  config:
    activate:
      on-profile: prod
inicis:
  mid: ${INICIS_MID}
  signKey: ${INICIS_SIGN_KEY}
  returnUrl: ${INICIS_RETURN_URL}
  closeUrl: ${INICIS_CLOSE_URL}
