logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

# 공통 설정
inicis:
  mid: INIpayTest
  signKey: SU5JTElURV9UUklQTEVERVNfS0VZU1RS
  version: ${INICIS_VERSION:1.0}
  payViewType: ${INICIS_PAY_VIEW_TYPE:popup}
  currency: ${INICIS_CURRENCY:WON}
  gopaymethod: ${INICIS_GOPAYMETHOD:Card}
  acceptmethod: ${INICIS_ACCEPTMETHOD:below1000}
  # 프론트 라우트로 복귀
  returnUrl: ${INICIS_RETURN_URL:http://localhost:3000/order/return}
  closeUrl: ${INICIS_CLOSE_URL:http://localhost:3000/order/close}

# 개발 환경
---
spring:
  config:
    activate:
      on-profile: dev
inicis:
  mid: ${INICIS_MID:INIpayTest}
  signKey: ${INICIS_SIGN_KEY:INIpayTest}
  returnUrl: ${INICIS_RETURN_URL:http://localhost:3000/order/return}
  closeUrl: ${INICIS_CLOSE_URL:http://localhost:3000/order/close}

# 검증(staging/test) 환경
---
spring:
  config:
    activate:
      on-profile: test
inicis:
  mid: ${INICIS_MID}
  signKey: ${INICIS_SIGN_KEY}
  returnUrl: ${INICIS_RETURN_URL}
  closeUrl: ${INICIS_CLOSE_URL}

# 운영 환경
---
spring:
  config:
    activate:
      on-profile: prod
inicis:
  mid: ${INICIS_MID}
  signKey: ${INICIS_SIGN_KEY}
  returnUrl: ${INICIS_RETURN_URL}
  closeUrl: ${INICIS_CLOSE_URL}
