logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

# 공통 설정
inicis:
  mid: INIpayTest
  signKey: SU5JTElURV9UUklQTEVERVNfS0VZU1RS
  apiKey: ItEQKi3rY7uvDS8l
  version: 1.0
  currency: WON
  gopaymethod: Card
  acceptmethod: below1000
  # 프론트엔드 팝업 페이지로 복귀 (POST body 처리)
  returnUrl: http://localhost:3000/order/progress-popup
  closeUrl: http://localhost:3000/order/close
  # 취소 API URL
  refundUrl: https://iniapi.inicis.com/v2/pg/refund

# 개발 환경
---
spring:
  config:
    activate:
      on-profile: dev
inicis:
  mid: ${INICIS_MID}
  signKey: ${INICIS_SIGN_KEY}
  apiKey: ${INICIS_API_KEY}
  returnUrl: ${INICIS_RETURN_URL}
  closeUrl: ${INICIS_CLOSE_URL}
  refundUrl: ${INICIS_REFUND_URL}

# 검증(staging/test) 환경
---
spring:
  config:
    activate:
      on-profile: test
inicis:
  mid: ${INICIS_MID}
  signKey: ${INICIS_SIGN_KEY}
  apiKey: ${INICIS_API_KEY}
  returnUrl: ${INICIS_RETURN_URL}
  closeUrl: ${INICIS_CLOSE_URL}
  refundUrl: ${INICIS_REFUND_URL}

# 운영 환경
---
spring:
  config:
    activate:
      on-profile: prod
inicis:
  mid: ${INICIS_MID}
  signKey: ${INICIS_SIGN_KEY}
  apiKey: ${INICIS_API_KEY}
  returnUrl: ${INICIS_RETURN_URL}
  closeUrl: ${INICIS_CLOSE_URL}
  refundUrl: ${INICIS_REFUND_URL}
